/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "autoscaler/multidimensional-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MultidimPodAutoscalerCheckpointLister helps list MultidimPodAutoscalerCheckpoints.
// All objects returned here must be treated as read-only.
type MultidimPodAutoscalerCheckpointLister interface {
	// List lists all MultidimPodAutoscalerCheckpoints in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MultidimPodAutoscalerCheckpoint, err error)
	// MultidimPodAutoscalerCheckpoints returns an object that can list and get MultidimPodAutoscalerCheckpoints.
	MultidimPodAutoscalerCheckpoints(namespace string) MultidimPodAutoscalerCheckpointNamespaceLister
	MultidimPodAutoscalerCheckpointListerExpansion
}

// multidimPodAutoscalerCheckpointLister implements the MultidimPodAutoscalerCheckpointLister interface.
type multidimPodAutoscalerCheckpointLister struct {
	indexer cache.Indexer
}

// NewMultidimPodAutoscalerCheckpointLister returns a new MultidimPodAutoscalerCheckpointLister.
func NewMultidimPodAutoscalerCheckpointLister(indexer cache.Indexer) MultidimPodAutoscalerCheckpointLister {
	return &multidimPodAutoscalerCheckpointLister{indexer: indexer}
}

// List lists all MultidimPodAutoscalerCheckpoints in the indexer.
func (s *multidimPodAutoscalerCheckpointLister) List(selector labels.Selector) (ret []*v1alpha1.MultidimPodAutoscalerCheckpoint, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MultidimPodAutoscalerCheckpoint))
	})
	return ret, err
}

// MultidimPodAutoscalerCheckpoints returns an object that can list and get MultidimPodAutoscalerCheckpoints.
func (s *multidimPodAutoscalerCheckpointLister) MultidimPodAutoscalerCheckpoints(namespace string) MultidimPodAutoscalerCheckpointNamespaceLister {
	return multidimPodAutoscalerCheckpointNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MultidimPodAutoscalerCheckpointNamespaceLister helps list and get MultidimPodAutoscalerCheckpoints.
// All objects returned here must be treated as read-only.
type MultidimPodAutoscalerCheckpointNamespaceLister interface {
	// List lists all MultidimPodAutoscalerCheckpoints in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MultidimPodAutoscalerCheckpoint, err error)
	// Get retrieves the MultidimPodAutoscalerCheckpoint from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.MultidimPodAutoscalerCheckpoint, error)
	MultidimPodAutoscalerCheckpointNamespaceListerExpansion
}

// multidimPodAutoscalerCheckpointNamespaceLister implements the MultidimPodAutoscalerCheckpointNamespaceLister
// interface.
type multidimPodAutoscalerCheckpointNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MultidimPodAutoscalerCheckpoints in the indexer for a given namespace.
func (s multidimPodAutoscalerCheckpointNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MultidimPodAutoscalerCheckpoint, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MultidimPodAutoscalerCheckpoint))
	})
	return ret, err
}

// Get retrieves the MultidimPodAutoscalerCheckpoint from the indexer for a given namespace and name.
func (s multidimPodAutoscalerCheckpointNamespaceLister) Get(name string) (*v1alpha1.MultidimPodAutoscalerCheckpoint, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("multidimpodautoscalercheckpoint"), name)
	}
	return obj.(*v1alpha1.MultidimPodAutoscalerCheckpoint), nil
}
