---
apiVersion: apiextensions.k8s.io/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: multidipodautoscalers.autoscaling.k8s.io
  annotations:
    "api-approved.kubernetes.io": "GitHub repo pull request link TBD"
spec:
  group: autoscaling.k8s.io
  scope: Namespaced
  names:
    plural: multidipodautoscalers
    singular: multidipodautoscaler
    kind: MultidiPodAutoscaler
    shortNames:
      - mpa
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: false
      storage: false
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required: []
          properties:
            scaleTargetRef:
              type: object
            updatePolicy:
              type: object
              properties:
                updateMode:
                  type: string
            goals:
              type: object
              properties:
                goalMetrics:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: ["CPUUtilization", "MemoryUtilization", "Latency", "Throughput"]
                      avgTarget:
                        type: float
            constraints:
              type: object
              properties:
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
            resourcePolicy:
              type: object
              properties:
                containerPolicies:
                  type: array
                  items:
                    type: object
                    properties:
                      containerName:
                        type: string
                      controlledValues:
                        type: string
                        enum: ["RequestsAndLimits", "RequestsOnly"]
                      mode:
                        type: string
                        enum: ["Auto", "Off"]
                      minAllowed:
                        type: object
                      maxAllowed:
                        type: object
                      controlledResources:
                        type: array
                        items:
                          type: string
                          enum: ["cpu", "memory"]
            recommenders:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
---
apiVersion: apiextensions.k8s.io/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalercheckpoints.autoscaling.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/63797"
spec:
  group: autoscaling.k8s.io
  scope: Namespaced
  names:
    plural: verticalpodautoscalercheckpoints
    singular: verticalpodautoscalercheckpoint
    kind: VerticalPodAutoscalerCheckpoint
    shortNames:
      - vpacheckpoint
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: false
      storage: false
