/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	v1alpha1 "k8s.io/autoscaler/multidimensional-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1alpha1"
	scheme "k8s.io/autoscaler/multidimensional-pod-autoscaler/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

// MultidimPodAutoscalerCheckpointsGetter has a method to return a MultidimPodAutoscalerCheckpointInterface.
// A group's client should implement this interface.
type MultidimPodAutoscalerCheckpointsGetter interface {
	MultidimPodAutoscalerCheckpoints(namespace string) MultidimPodAutoscalerCheckpointInterface
}

// MultidimPodAutoscalerCheckpointInterface has methods to work with MultidimPodAutoscalerCheckpoint resources.
type MultidimPodAutoscalerCheckpointInterface interface {
	Create(ctx context.Context, multidimPodAutoscalerCheckpoint *v1alpha1.MultidimPodAutoscalerCheckpoint, opts v1.CreateOptions) (*v1alpha1.MultidimPodAutoscalerCheckpoint, error)
	Update(ctx context.Context, multidimPodAutoscalerCheckpoint *v1alpha1.MultidimPodAutoscalerCheckpoint, opts v1.UpdateOptions) (*v1alpha1.MultidimPodAutoscalerCheckpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MultidimPodAutoscalerCheckpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MultidimPodAutoscalerCheckpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultidimPodAutoscalerCheckpoint, err error)
	MultidimPodAutoscalerCheckpointExpansion
}

// multidimPodAutoscalerCheckpoints implements MultidimPodAutoscalerCheckpointInterface
type multidimPodAutoscalerCheckpoints struct {
	client rest.Interface
	ns     string
}

// newMultidimPodAutoscalerCheckpoints returns a MultidimPodAutoscalerCheckpoints
func newMultidimPodAutoscalerCheckpoints(c *AutoscalingV1alpha1Client, namespace string) *multidimPodAutoscalerCheckpoints {
	return &multidimPodAutoscalerCheckpoints{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multidimPodAutoscalerCheckpoint, and returns the corresponding multidimPodAutoscalerCheckpoint object, and an error if there is any.
func (c *multidimPodAutoscalerCheckpoints) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultidimPodAutoscalerCheckpoint, err error) {
	result = &v1alpha1.MultidimPodAutoscalerCheckpoint{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultidimPodAutoscalerCheckpoints that match those selectors.
func (c *multidimPodAutoscalerCheckpoints) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultidimPodAutoscalerCheckpointList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MultidimPodAutoscalerCheckpointList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multidimPodAutoscalerCheckpoints.
func (c *multidimPodAutoscalerCheckpoints) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a multidimPodAutoscalerCheckpoint and creates it.  Returns the server's representation of the multidimPodAutoscalerCheckpoint, and an error, if there is any.
func (c *multidimPodAutoscalerCheckpoints) Create(ctx context.Context, multidimPodAutoscalerCheckpoint *v1alpha1.MultidimPodAutoscalerCheckpoint, opts v1.CreateOptions) (result *v1alpha1.MultidimPodAutoscalerCheckpoint, err error) {
	result = &v1alpha1.MultidimPodAutoscalerCheckpoint{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multidimPodAutoscalerCheckpoint).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a multidimPodAutoscalerCheckpoint and updates it. Returns the server's representation of the multidimPodAutoscalerCheckpoint, and an error, if there is any.
func (c *multidimPodAutoscalerCheckpoints) Update(ctx context.Context, multidimPodAutoscalerCheckpoint *v1alpha1.MultidimPodAutoscalerCheckpoint, opts v1.UpdateOptions) (result *v1alpha1.MultidimPodAutoscalerCheckpoint, err error) {
	result = &v1alpha1.MultidimPodAutoscalerCheckpoint{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		Name(multidimPodAutoscalerCheckpoint.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(multidimPodAutoscalerCheckpoint).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the multidimPodAutoscalerCheckpoint and deletes it. Returns an error if one occurs.
func (c *multidimPodAutoscalerCheckpoints) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multidimPodAutoscalerCheckpoints) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched multidimPodAutoscalerCheckpoint.
func (c *multidimPodAutoscalerCheckpoints) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultidimPodAutoscalerCheckpoint, err error) {
	result = &v1alpha1.MultidimPodAutoscalerCheckpoint{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multidimpodautoscalercheckpoints").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
